{% set name = "divemesh" %}
{% set version = "23.08" %}
{% set sha256 = "d67c287793da9972e6d4a4dd0cc281816382ea325a308ef434522e8d71993ed4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/REEF3D/DIVEMesh/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports_from:
    - {{ compiler('cxx') }}  # [osx]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f $PREFIX/bin/divemesh
    - divemesh

about:
  home: https://reef3d.wordpress.com/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "DIVEMesh : the mesh generator for REEF3D"

extra:
  recipe-maintainers:
    - mattkram
