{% set name = "divemesh" %}
{% set version = "26.01" %}
{% set sha256 = "d87586e4051ee8c527d619d646f27ed5298c0bf3a82a20c7ddd565e77c2e15b8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/REEF3D/DIVEMesh/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports_from:
    - {{ compiler('cxx') }}  # [osx]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

test:
  commands:
    - test -f $PREFIX/bin/divemesh

about:
  home: https://reef3d.wordpress.com/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "DIVEMesh : the mesh generator for REEF3D"

extra:
  recipe-maintainers:
    - mattkram
