{% set name = "divemesh" %}
{% set version = "25.05" %}
{% set sha256 = "b607e354f0b84052222c8c2146947192df758d9d67859d9b72c777b546637538" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/REEF3D/DIVEMesh/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports_from:
    - {{ compiler('cxx') }}  # [osx]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

test:
  commands:
    - test -f $PREFIX/bin/divemesh
    - divemesh

about:
  home: https://reef3d.wordpress.com/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "DIVEMesh : the mesh generator for REEF3D"

extra:
  recipe-maintainers:
    - mattkram
